project:
  type: website
  output-dir: docs

website:
  title: "Marcin Kierczak"
  navbar:
    left:
      - href: index.qmd
        text: Hus
      - href: teaching.qmd
        text: Teachings
      - href: writings.qmd
        text: Writings
      - href: blog.qmd
        text: Saga

format:
  html:
    theme: 
      - mono
      - assets/custom.scss
    toc: true

editor: source

